### ISSUE TITLE
Proxy support?

### ISSUE THREAD

**Issue by antfuentes87** [BosslandGmbH/HBRelog#24]
I know this is not really a issue, but any possible way to be able to have a proxy support for each individual profile you create? So that way you can set a different proxy for each one, and launch more than 1 WoW at a time under different proxies? Have no clue if it is even possible, but figure I would throw it out there.

**Comment by shpilim** [comment]
I have a solution. But its pricy. Skype Id = shpel1.
Also i have auto character creation. Both integrated.

**Comment by highvoltz** [comment]
You can have HBRelog start a custom launcher instead of WoW.exe and this launcher could enable proxy usage for the WoW process. Making this a buildin feature of HBRelog is unlikely though because of difficulty and security issues
