### ISSUE TITLE
Wow Start Delay

### ISSUE THREAD

**Issue by DrNeed** [BosslandGmbH/HBRelog#25]
**Now:** After one instance finished to start the next one begins to start. Wow Start Delay - delay between one instance **finished** to start and the next one begins.

**What would be fine:** Wow Start Delay - delay between one instance **began** to start and the next one begins.

**Why:** Sometimes one instance can't finish starting (bad connection problem, for example), and because of it other instances in a queue can't start too.

P.S. Sorry for my English. I hope I explained what I mean ))

**Comment by highvoltz** [comment]
I can't implement it this way because only one WoW instance can be logged in at one time per WoW install folder due to the method HBRelog uses to login. (Modification of WoW's WTF settings).
