### ISSUE TITLE
При запуске Релогера выскакивает следующая ошибка

### ISSUE THREAD

**Issue by Timoshok** [BosslandGmbH/HBRelog#29]
![default](https://cloud.githubusercontent.com/assets/23523719/20390358/8ea5dc5c-acdf-11e6-8fd1-455ccdc190ea.png)

**Comment by highvoltz** [comment]
I don't understand what the error popup window is saying.

**Comment by Timoshok** [comment]
Сигнатура проблемы:
  Имя события проблемы:	CLR20r3
  Сигнатура проблемы 01:	HBRelog.exe
  Сигнатура проблемы 02:	1.1.12.0
  Сигнатура проблемы 03:	581cb0ed
  Сигнатура проблемы 04:	HBRelog
  Сигнатура проблемы 05:	1.1.12.0
  Сигнатура проблемы 06:	581cb0ed
  Сигнатура проблемы 07:	3cc
  Сигнатура проблемы 08:	0
  Сигнатура проблемы 09:	System.TypeInitialization
  Версия ОС:	6.1.7601.2.1.0.256.1
  Код языка:	1049
  Дополнительные сведения 1:	0a9e
  Дополнительные сведения 2:	0a9e372d3b4ad19135b953a78882e789
  Дополнительные сведения 3:	0a9e
  Дополнительные сведения 4:	0a9e372d3b4ad19135b953a78882e789

Ознакомьтесь с заявлением о конфиденциальности в Интернете:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0419

Если заявление о конфиденциальности в Интернете недоступно, ознакомьтесь с его локальным вариантом:
  C:\Windows\system32\ru-RU\erofflps.txt
Вот если открыть ошибку

**Comment by highvoltz** [comment]
Your .net installation might be corrupt. Try reinstalling .[net 4.6.1](https://www.microsoft.com/en-us/download/details.aspx?id=49982), and if that doesn't work, reinstall [Visual C++ Redistributable](https://www.microsoft.com/en-us/download/details.aspx?id=49982)

**Comment by Timoshok** [comment]
Я пробывал обновлять но не перезагружал. Спасибо большое буду пробывать ещё раз
Может антивирус? блокирует я имею ввиду

**Comment by Timoshok** [comment]
Все включился. Помоги настроить релогер для прокачки до 110 уровня
