### ISSUE TITLE
Mess with process id.

### ISSUE THREAD

**Issue by shpilim** [BosslandGmbH/HBRelog#34]
Sometimes it starts HB and tries to attach it to dead wow process.
It thinks its alive but its ask another process if its alive.
How do i know if it asks another process? Its easy. When i press stop it closed absolutely different profile then that i've actually stopped. And then they both start their wow.exe and continue working.
Could you please fix that?

**Comment by highvoltz** [comment]
Does your HBRelog profile start WoW.exe directly and/or does it have any tasks? Could you attach the HBLog log file?

**Comment by shpilim** [comment]
1. Yes directly
2. No there's no taks at all
3. Log http://dropmefiles.com/TRcLP

**Comment by shpilim** [comment]
Now HBrelog starts hb even if char is on login screen.
I think you need to fix or to add more checks before starting HB.

**Comment by shpilim** [comment]
I've sent you video on HB forum with this bug.
Btw its very old. Have no idea why there's no reports.
Asked few friends about this and they confirmed.
