### ISSUE TITLE
stuck when characterselect

### ISSUE THREAD

**Issue by ybhuxiao** [BosslandGmbH/HBRelog#36]
<img src="https://github.com/ybhuxiao/HBRelog/blob/master/issue.jpg?raw=true" />

if this confirmdialog is visible, hbrelog can not change the server/realm, so hbrelog got stuck.
it seems like wow's bug.

could hbrelog shutdown wow client when this confirmdialog visible.

**Comment by marrvin2** [comment]
Hi Highvolts,
although this is fixed now I have  investigated this error:

The "Login Delay"- counter starts running as soon as the "Login" Button is pressed .. so the delay will expire during wow-client showing "Connecting"
(need up to 10 seconds on EU)

So the "Switch Realm" Button is pressed IMMEDIATLY after it is barley visible. 
Adding a small delay after "Connecting" prior pressing the "switch realm" button will reduce the change of Error WOW51900329  by a huge amount!

My solution "hack" was:
I added  a 4 Second  Thread Sleep  just before the button is pressed in
ChangeRealm()  in CharacterSelectState.cs 
:D
