### ISSUE TITLE
wait state is not waiting

### ISSUE THREAD

**Issue by ybhuxiao** [BosslandGmbH/HBRelog#40]
[Log[2017-10-08_05-24-31].txt](https://github.com/BosslandGmbH/HBRelog/files/1366758/Log.2017-10-08_05-24-31.txt)

this waiting should wait for 50 minutes, but not.
![qq 20171008172816](https://user-images.githubusercontent.com/17189297/31315631-b7708ee2-ac4e-11e7-83a7-8f69499b5e5b.jpg)

![image](https://user-images.githubusercontent.com/17189297/31315644-dbca960c-ac4e-11e7-8726-0388de7b9583.png)

**Comment by ybhuxiao** [comment]
i think test1 should start test2 task and wait, but test1 start itself..

![qq 20171008171950](https://user-images.githubusercontent.com/17189297/31315647-09fdb72a-ac4f-11e7-8a37-a928c1c11361.jpg)

![qq 20171008171955](https://user-images.githubusercontent.com/17189297/31315648-0d066e62-ac4f-11e7-8c27-bda9b8f10caa.jpg)

**Comment by highvoltz** [comment]
If you're wanting WoW to stay logged out then you'll need to use an Idle task at the bottom of profile 'test1'

**Comment by highvoltz** [comment]
This isn't a bug. 'Wait' task is just adds a delay before next task is executed. if you want bot to stay logged out you'll have to use idle task.

**Comment by ybhuxiao** [comment]
ty, i will try it
