### ISSUE TITLE
it wont skip tasks now 

### ISSUE THREAD

**Issue by bobbe520** [BosslandGmbH/HBRelog#41]
before 7.3 when finish all the WQ with Treasure Hunter  hbrelog would skip the task to next ,but now it wont ,seems like it would wait untill the 'wait' time I set

**Comment by highvoltz** [comment]
Do you have an HBRelog and HB log of this occurring?

**Comment by bobbe520** [comment]
[Log[2017-10-09_03-39-30].txt](https://github.com/BosslandGmbH/HBRelog/files/1369755/Log.2017-10-09_03-39-30.txt)

**Comment by bobbe520** [comment]
[5472 2017-10-09 03.58.txt](https://github.com/BosslandGmbH/HBRelog/files/1369761/5472.2017-10-09.03.58.txt)

**Comment by bobbe520** [comment]
not sure which one can help ,and there us always some red code about HBRlog when loading HB 
[1100 2017-10-09 17.02.txt](https://github.com/BosslandGmbH/HBRelog/files/1369777/1100.2017-10-09.17.02.txt)

**Comment by highvoltz** [comment]
I think the new HBRelog release (v1.1.22) will fix this. You can get it here https://github.com/BosslandGmbH/HBRelog/releases/latest.

**Comment by highvoltz** [comment]
This issue was caused by outdated 3rd party code it's fixed with #44
