### ISSUE TITLE
HBRelog 1.23 not detecting disconnected Wow window

### ISSUE THREAD

**Issue by vipery** [BosslandGmbH/HBRelog#45]
No log because nothin to log =) Disconneted Wow window just stay disconnect without relog

Checkbox hb andd wow responsive already set

**Comment by highvoltz** [comment]
Did you pause HBRelog at anytime after it had launched WoW? Was HB stopped when WoW disconnected?

**Comment by vipery** [comment]
Sure no. I have 20 sessions = Random disconnects its okay.
But HBRelog Status line keep show hb's tasks and never restart them

**Comment by highvoltz** [comment]
Ok, I think I know the issue. I'll post back when I have a new release ready

**Comment by highvoltz** [comment]
The new v.1.1.24 release fixes this issue

**Comment by vipery** [comment]
Thanks!
