### ISSUE TITLE
"Pause" not working as intended

### ISSUE THREAD

**Issue by AionLtd** [BosslandGmbH/HBRelog#48]
Hello. 
I'm curious if the latest HBRelog "Pause" behavior is intended change or a bug:
When launch certain Bot +HB with HBRelog task, I pause it, after HB have been attached.
But HBRelog operates just like it have not been paused. 
- Kills wow once character is disconnected and attempt restart, but since its paused it does nothing after.
For example:
> [21:24:07] WoWBot1: Restarting wow because it was logged out for more than 40 seconds
> [21:24:14] WoWBot2: Restarting wow because it was logged out for more than 40 seconds
- When "Wait" timer tick off, it launch the next task, usually "Idle" or "Logon" 
- When the profile send HBRelog Skip command, it responds.
For example:
> [21:42:02] WoWBot1: Opened communication with HBRelogHelper
> [21:42:24] WoWBot1: Could not skip current task because there is no task running.
> 
> [21:39:52] WoWBot2: Opened communication with HBRelogHelper
> [21:39:53] WoWBot2: Waiting for 600 minutes before executing next task
> [21:40:38] WoWBot2: Skipping the "Wait" task.
> [21:40:39] WoWBot2: Idling for 1200 minutes before executing next task
All of those, while the corresponding HBRelog profile is being paused.
These features were always disabled, while paused in the past.

**Comment by highvoltz** [comment]
> When "Wait" timer tick off, it launch the next task, usually "Idle" or "Logon
I can only see this being possible when 'SkipCurrentTask is being called. The tasks are not getting pulsed while the profile is paused.

**Comment by AionLtd** [comment]
Thanks ;)
